### ISSUE TITLE
Wiki Macros are not working in version 2.1.0 with Redmine 2.0.3

### ISSUE THREAD

**Issue by dpeter** [alexbevi/redmine_knowledgebase#91]
When I try to reference a knowledgebase article from a wiki page with like this:

```
{{kb(6)}}
{{article_id(6)}}
{{article(6)}}
{{category(1)}}
```

I get these error messages:

```
Error executing the kb macro (undefined method `link_to_article' for #<#:0x2860ad93>)
Error executing the article_id macro (undefined method `link_to_article' for #<#:0x2860ad93>)
Error executing the article macro (undefined method `link_to_article_with_title' for #<#:0x8717ab8a>)
Error executing the category macro (undefined method `link_to_category_with_title' for #<#:0x2860ad93>)
```

I checked with the wiki macro `{{macro_list}}` if the macros are available and got this output:

```
article

    Knowledge base Article link Macro, using the article# format

article_id

    Knowledge base Article link Macro, using the article_id# format

category

    Knowledge base Category link Macro, using the category# format

kb

    Knowledge base Article link Macro, using the kb# format
```

When I use the wiki macros in a kb article, the links work but they are not labled correctly - only the `{{category(<category_id>)}}` is labled corectly. These are the labels I get in the rendered output:

```
KB#{{kb_id}}

KB#{{kb_id}}

KB#{{kb_id}}: Some KB Artice
```

Here are the software version:

```
$ jruby -S script/about

Environment:
  Redmine version                          2.0.3.stable
  Ruby version                             1.8.7 (java)
  Rails version                            3.2.6
  Environment                              production
  Database adapter                         PostgreSQL
Redmine plugins:
  redmine_knowledgebase                    2.1.0

$ jruby -v
jruby 1.6.7.2 (ruby-1.8.7-p357) (2012-05-01 26e08ba) (IBM J9 VM 1.7.0) [AIX-ppc-java]

```
