### ISSUE TITLE
Problems after upgrading from 2.2.0 to 3.0 devel

### ISSUE THREAD

**Issue by ghost** [alexbevi/redmine_knowledgebase#144]
Hi,

Thanks for this great plugin. I was using version 2.2.0 of the redmine_knowledgebase plugin on Bitnami redmine stack. Everything worked to some extent except the browsing of by tags. So I decided to upgrade to the latest 3.0 devel hoping things were fixed. By the way, I already had a couple of articles in my system (using the previous 2.2.0 version). After the upgrade, I get a 500 Http error when I try to view my articles. I have the following in the logs:

Started GET "/redmine/projects/com-r2d2-general-information/knowledgebase/articles/2" for 91.65.251.146 at 2013-01-28 14:31:24 +0100
Processing by ArticlesController#show as HTML
  Parameters: {"project_id"=>"com-r2d2-general-information", "id"=>"2"}
  Current user: admin (id=1)
  Rendered plugins/redmine_knowledgebase/app/views/articles/show.html.erb within layouts/base (100.0ms)
Completed 500 Internal Server Error in 118ms

ActionView::Template::Error (undefined method `watcher_tag' for #<#<Class:0x58fcb18>:0x5950b60>):
    10:         <li><%= link_to_if_authorized l(:label_edit_article), { :controller => 'articles', :action => 'edit', :id => @article.id, :project_id => @project}, :class => 'icon icon-edit' %></li>
    11:         <li><%= link_to_if_authorized l(:label_delete_article), { :controller => 'articles', :action => 'destroy', :id => @article.id, :project_id => @project}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %></li>
    12:         <li><%= link_to_if_authorized l(:label_new_comment), { :controller => "articles", :action => "comment", :article_id => @article.id, :project_id => @project}, :class => "icon icon-comment", :remote => true, :method => :get %></li>
    13:         <li><%= watcher_tag(@article, User.current) %></li>
    14:     </ul>
    15:     <br />
    16:   <div id='rating-container'>
  app/helpers/application_helper.rb:1190:in`content_for'

Do you know what is going on here? We have spent so much time writing these articles and it would majorly suck to lose them. By the way I have a backup of my database before the migration. What are my options? Can someone help? Would it also be possible to downgrade by to 2.2.0? Thanks.

Charlie.

**Comment by ruby-adictive** [comment]
`watcher_tag` method is replaced with `watcher_list`
